// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kgjncxvhjlfrtkvdaydg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imtnam5jeHZoamxmcnRrdmRheWRnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQzMDE5MjksImV4cCI6MjA2OTg3NzkyOX0.tSITt_G_Gpl_YBx9VqgirxR9JaiLneb4TDInxp9KI0U";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});